apiVersion: v1
kind: Service
metadata:
  name: breizhsport-service
spec:
  type: NodePort
  selector:
    app: breizhsport
  ports:
    - name: backend
      port: 8000
      targetPort: 8000
      nodePort: 30000
    - name: frontend
      port: 5173
      targetPort: 5173
      nodePort: 30001
