name: POC Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-laravel:
    runs-on: self-hosted
    steps:
    #- uses: shivammathur/setup-php@15c43e89cdef867065b0213be354c2841860869e
    #  with:
    #    php-version: '8.2'
    #- name: Setup Node.js environment
    #  uses: actions/setup-node@v3.9.1
    - uses: actions/checkout@v4
    - name: Copy .env
      run: php -r "file_exists('.env') || copy('.env.example', '.env');"
    - name: Install Dependencies
      run: composer install
    - name: Generate key
      run: php artisan key:generate
    - name: Directory Permissions
      run: chmod -R 777 storage bootstrap/cache
    - name: Create Database
      run: |
        mkdir -p database
        touch database/database.sqlite
    - name: Migrate
      run: php artisan migrate
    - name: Migrate-seed
      run: php artisan migrate --seed
    - name: Npm install
      run: npm install
    - name: Start npm
      run: npm run build
    - name: Start artisan
      run : php artisan test
      
  build-docker:
    needs: build-laravel
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v4
    #- name: Docker login
    #  env:
    #    DOCKER_LOGIN: ${{ secrets.DOCKER_LOGIN }}
    #    DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
    #  run: docker login -u $DOCKER_LOGIN -p $DOCKER_PASSWORD
    - name: Build the Docker image
      run: docker build -t letibodoh/breizhsport .
    - name: Docker push
      run: docker image push letibodoh/breizhsport

  minikube-deploy:
    needs: build-docker
    runs-on: self-hosted
    steps:
    - name: Minikube delete
      run: minikube delete
    - name: Minikube start
      run: minikube start --driver=docker --ports=30000:30000,30001:30001
    - name: Minikube apply service
      run: kubectl apply -f service.yaml | kubectl apply -f pod.yaml
